name: DartWebServerDemo
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Administrator <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.3+3
  http_server: ^0.9.8
  crypto: ^2.0.6
  hex: ^0.1.2

#dev_dependencies:
#  test: ^1.0.0
